apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tmp-cache
  labels:
    app: soft-prompt-remote
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soft-prompt-remote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soft-prompt-remote
  template:
    metadata:
      labels:
        app: soft-prompt-remote
    spec:
      containers:
      - name: soft-prompt-remote
        image: registry.datexis.com/s91000/bender-remote:0.0.1
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: general-data
          mountPath: /data
        - name: ssh-key
          mountPath: /root/ssh-key
        - name: root-temp
          mountPath: /root
        - name: tmp-cache
          mountPath: /tmp
        ports:
          - containerPort: 22
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cat /root/ssh-key/id_rsa.pub >> /root/.ssh/authorized_keys"]
        resources:
          requests:
            nvidia.com/gpu: 2
            cpu: 2
          limits:
            nvidia.com/gpu: 2
            cpu: 16
      nodeSelector:
        kubernetes.io/hostname: cl-worker29
        gpu: a100
  #      tolerations:
  #      - operator: "Exists"
  #      - key: "nvidia.com/gpu"
      imagePullSecrets:
      - name: private-registry-auth
      volumes:
        - name: ssh-key
          secret:
            secretName: my-ssh-public-key
            defaultMode: 256
        - name: general-data
          persistentVolumeClaim:
            claimName: general-data
        - name: root-temp
          persistentVolumeClaim:
            claimName: root-temp
        - name: tmp-cache
          persistentVolumeClaim:
            claimName: tmp-cache

