apiVersion: batch/v1
kind: Job
metadata:
  name: soft-prompt-mistral
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: soft-prompt-mistral
          image: registry.datexis.com/s91000/thesis-tuning:0.0.9
          command: ["/bin/sh", "-c"]
#          args: ["cd data && pip install &&  python code/segment_articles.py"]
          args: ["cd data && pip install accelerate tensorboardX -U && pip install \"dill<0.3.5\" && CUDA_LAUNCH_BLOCKING=1 python code/main_no_class.py"]
          volumeMounts:
            - name: general-data
              mountPath: /tuning/data
            - name: root-temp
              mountPath: /root
#            - name: ray-pvc
#              mountPath: /pvc
#            - name: ssh-key
#              mountPath: /root/ssh-key
          ports:
#            - containerPort: 12345 # Ray internal communication.
#            - containerPort: 12346 # Ray internal communication.
            - containerPort: 22
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  resource: requests.cpu
            - name: MODEL_NAME
              value: 'mistralai/Mistral-7B-v0.3'
              #              'google/gemma-7b'
              #              'meta-llama/Meta-Llama-3-8B'
              #                'mistralai/Mistral-7B-v0.3'
              #            "openlm-research/open_llama_13b"
            - name: HF_TOKEN
              value: "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"
            - name: DATASET_PATH
              value: 'data/datasets/queer_news.hf'
            - name: MODE
              value: "soft-prompt"
            - name: PROMPT_LENGTH
              value: "10"
            - name: OUTPUT_FILE
              value: "output.txt"
            - name: CHUNK_SIZE
              value: "1000"
            - name: LM_MODEL_PATH
              value: "google/gemma-7b"
            - name: REDUCE_DATASET
              value: "0"
            - name: BATCH_SIZE
              value: "8"
            - name: EPOCHS
              value: "1"
            - name: LEARNING_RATE
              value: "0.00002"
          resources:
            requests:
              nvidia.com/gpu: 1
              cpu: 1
              memory: 10Gi
            limits:
              nvidia.com/gpu: 1
              memory: 250Gi
              cpu: 2
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never
      nodeSelector:
        gpu: a100
      volumes:
        - name: general-data
          persistentVolumeClaim:
            claimName: general-data
#        - name: ssh-key
#          secret:
#            secretName: my-ssh-public-key
#            defaultMode: 256
        - name: root-temp
          persistentVolumeClaim:
            claimName: root-temp